# Generated by Django 4.2.3 on 2023-07-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_text_text_text_text1_text_text2_text_text3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text3',
        ),
    ]
